language: node_js
node_js:
- '7.7'
branches:
  only:
  - master
install:
- yarn install
- yarn run build
deploy:
  provider: s3
  access_key_id: AKIAJKORYBAKP62VPKBA
  secret_access_key:
    secure: vBi1NmsQPgijaN3BSDeiul3wsld+6HyYySJcVg+llHbkE8zMN+iyZAz2fBqAF/ijGVxT5nDBkr5VCpSwGNBEbZ9J0GAEFLaQAn6J5Otn7DLaq7NqEIxuVXskYPX99kULr69lvJ+tl0rew4C8tree+P9uYUgqtOicsNJNTgY9sGBKN3XHQ+Zd80oeFBICbLdD5zk6xd8V7P5otY5hcdG9MkfPKwipvFKIOkKB2VcKxl2geK8Cu3EliPiATUgxfSIonja1A1OC6eGQseSNJwAEv+Ipw4pXcFuPXIytTyybkkC346ldXFncQBvkPAMttmS/y3KHaw7cFXS9Dfn4hau+P9BCZ5/+nMp3HRcluTE3bZFrAiTpR5rV7SozE9rloCZJBkQJBHu9coHJXB7VRtQYMYHT7jFVJefq0rV29eBFHU7bxJ6UNhCHBz+Q5RqdO5ZSxJjZSnvV4TXZdk0x53Ki0fkceZGnMR9RcgSsqF8JKbENXgiL+TK48c013N271C47OSAzmmDW4VzxbpH/B3bg/TPl86mAk06zNhS6gfOcIDQvlFtwHbY7in2JG97Ams8j5YrRtPeLT1dqNCclVbf65Xh/u4mup8dmKJytyyUl2Ng8zNnfXvJWPWA9VlbZiDWXctfk6cPV48B9iinG2t7VNKdDNpuNLypM4VqfcZFEsJk=
  bucket: instaclone.sourgrapes.io
  region: us-east-2
  skip_cleanup: true
  local-dir: build
  acl: public_read
  cache_control: no-cache
  on:
    repo: mcorrigan89/instaclone-client
