language: node_js
node_js:
- '7.7'
branches:
  only:
  - master
install:
- yarn install
- yarn run build
deploy:
  provider: s3
  access_key_id: AKIAJKORYBAKP62VPKBA
  secret_access_key:
    secure: N0qm8yCgmz5JhvZvaImIsHfkfF3YG0gaCciXof9E+VVNSYjR+K+WD5WH3ePh2ABVKc8q5wq2MOuSpWZEFT/lwhqdJPQwhHLbzhepIEMaof1VvXLzUa/koYqgOrjxQerZX//96BKPIUUiclJwMK/NaBCL6FQwwXgnOiJelSQTcuOll35k4hElJsBu2Wpo0PMbEVV0MLoPKYhfI0yGr833KhllFEDE54sV8X7RvcA3WzAZhgquSQSCdlnOeuZCqPraA1XUSGoYk34gq6Erp9mon0U7W9MhsI+Pf5ycZf0OLmy+XKGoELdM7LtxWheKbBnLoauEEQUoLo1rXmCjbhZOMBkeBzF342NaDx7c72MdEg7agyUsifvUCHCk8c7KWiBB0VpjQVUgUmfhfzhJiBuzxVxHHPbjjD/6pH/z9Xd1Pcu2D4KveEZ01mvje4pZzRdY9pgyVUHjEwYj3xneoDnKZX1YwWilU9JzA4WEJMnJbjVl1vZdfbji16OL2wsVTsMPZnPk7zqzMXPfML0vZ6YuOZDeTpFr2wVe+tXuow624/B7vTOvd28PdmHsUilJCerIjtPSGDo1cT8K2TCQjMgC5eXy0LjNzMmpufJVEFHQ7xKWoA5hq8+G7YLasUqNODZ7FtEosjTzZ9mDWNyzRSFjGVIm+eOx3qvBuZzOStf9bqA=
  bucket: instaclone.sourgrapes.io
  region: us-west-2
  skip_cleanup: true
  local-dir: build
  acl: public_read
  cache_control: no-cache
  on:
    repo: mcorrigan89/instaclone-client